public enum ClickFixErrorCode: String, Codable, Sendable {
    case sensorNotInstalled = "CFX001_SENSOR_NOT_INSTALLED"
    case sensorNotRunning = "CFX002_SENSOR_NOT_RUNNING"
    case inputMonitoringDenied = "CFX003_INPUT_MONITORING_DENIED"
    case accessibilityDenied = "CFX004_ACCESSIBILITY_DENIED"
    case clipboardAccessDenied = "CFX005_CLIPBOARD_ACCESS_DENIED"
    case clipboardReadTimeout = "CFX006_CLIPBOARD_READ_TIMEOUT"
    case clipboardTooLarge = "CFX007_CLIPBOARD_TOO_LARGE"
    case classificationFailed = "CFX008_CLASSIFICATION_FAILED"
    case classifierSignatureInvalid = "CFX009_CLASSIFIER_SIGNATURE_INVALID"
    case eventTapDisabled = "CFX010_EVENT_TAP_DISABLED"
    case eventTapTimeout = "CFX011_EVENT_TAP_TIMEOUT"
    case xpcAuthenticationFailed = "CFX012_XPC_AUTHENTICATION_FAILED"
    case eventQueueOverflow = "CFX013_EVENT_QUEUE_OVERFLOW"
    case evidencePersistenceFailed = "CFX014_EVIDENCE_PERSISTENCE_FAILED"
    case shortcutReplayFailed = "CFX015_SHORTCUT_REPLAY_FAILED"
    case clipboardQuarantineFailed = "CFX016_CLIPBOARD_QUARANTINE_FAILED"
    case notificationDeliveryFailed = "CFX017_NOTIFICATION_DELIVERY_FAILED"
    case correlationSensorUnavailable = "CFX018_CORRELATION_SENSOR_UNAVAILABLE"
    case endpointSecurityUnavailable = "CFX019_ENDPOINT_SECURITY_UNAVAILABLE"
    case protectModeDegraded = "CFX020_PROTECT_MODE_DEGRADED"
}
