from __future__ import annotations

from mac_audit_agent.models import AuditCommand


def _command(
    *,
    command_id: str,
    name: str,
    description: str,
    argv: list[str],
    category: str,
    risk_level: str = "safe",
    timeout_seconds: int = 10,
    collection_warning: str,
    failure_modes: list[str],
    user_disclaimer: str,
    safer_alternative: str,
) -> AuditCommand:
    return AuditCommand(
        id=command_id,
        name=name,
        description=description,
        command=argv,
        privilege_required=False,
        risk_level=risk_level,  # type: ignore[arg-type]
        mutates_system=False,
        timeout_seconds=timeout_seconds,
        collection_warning=collection_warning,
        failure_modes=failure_modes,
        user_disclaimer=user_disclaimer,
        safer_alternative=safer_alternative,
        category=category,
    )


def build_command_registry() -> dict[str, AuditCommand]:
    commands = [
        _command(
            command_id="persistence.user_launch_agents",
            name="User LaunchAgents",
            description="Lists per-user LaunchAgents that run at login.",
            argv=["/bin/ls", "-la", "~/Library/LaunchAgents"],
            category="Persistence",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="File names may reveal installed software or management tooling.",
            failure_modes=["Directory does not exist.", "Permission denied."],
            user_disclaimer="Read-only listing only; no plist contents are modified.",
            safer_alternative="Inspect the directory manually in Finder.",
        ),
        _command(
            command_id="persistence.system_launch_agents",
            name="System LaunchAgents",
            description="Lists system LaunchAgents.",
            argv=["/bin/ls", "-la", "/Library/LaunchAgents"],
            category="Persistence",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="File names may reveal installed software or management tooling.",
            failure_modes=["Directory does not exist.", "Permission denied."],
            user_disclaimer="Read-only listing only.",
            safer_alternative="Inspect the directory manually in Finder.",
        ),
        _command(
            command_id="persistence.system_launch_daemons",
            name="System LaunchDaemons",
            description="Lists system LaunchDaemons.",
            argv=["/bin/ls", "-la", "/Library/LaunchDaemons"],
            category="Persistence",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="File names may reveal installed software or management tooling.",
            failure_modes=["Directory does not exist.", "Permission denied."],
            user_disclaimer="Read-only listing only.",
            safer_alternative="Inspect the directory manually in Finder.",
        ),
        _command(
            command_id="persistence.login_items",
            name="Login Items",
            description="Reads configured login items via System Events.",
            argv=["/usr/bin/osascript", "-e", 'tell application "System Events" to get the name of every login item'],
            category="Persistence",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="App names configured for login may be sensitive.",
            failure_modes=["Automation permission denied.", "System Events unavailable."],
            user_disclaimer="Read-only query of configured login item names.",
            safer_alternative="Review Login Items in System Settings.",
        ),
        _command(
            command_id="persistence.cron_tabs",
            name="Cron And At Jobs",
            description="Lists legacy cron and at job locations commonly abused for persistence.",
            argv=["/bin/ls", "-la", "/usr/lib/cron/tabs", "/var/at/tabs", "/private/var/at/tabs"],
            category="Persistence",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="May reveal local account names with scheduled jobs.",
            failure_modes=["Directories may not exist.", "Permission denied for per-user job stores."],
            user_disclaimer="Read-only listing of legacy scheduled-job locations.",
            safer_alternative="Inspect scheduled-job directories manually with administrator approval.",
        ),
        _command(
            command_id="persistence.periodic_scripts",
            name="Periodic Scripts",
            description="Lists periodic script directories used by legacy scheduled maintenance.",
            argv=["/bin/ls", "-la", "/etc/periodic", "/private/etc/periodic"],
            category="Persistence",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="File names may reveal installed maintenance tooling.",
            failure_modes=["Directories may not exist.", "Permission denied."],
            user_disclaimer="Read-only listing only; scripts are not executed.",
            safer_alternative="Inspect periodic script paths manually.",
        ),
        _command(
            command_id="persistence.scripting_additions",
            name="Scripting Additions",
            description="Lists AppleScript scripting additions that can extend automation behavior.",
            argv=["/bin/ls", "-la", "/Library/ScriptingAdditions", "~/Library/ScriptingAdditions"],
            category="Persistence",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="File names may reveal automation or management tooling.",
            failure_modes=["Directories may not exist.", "Permission denied."],
            user_disclaimer="Read-only listing of scripting addition locations.",
            safer_alternative="Inspect ScriptingAdditions folders manually.",
        ),
        _command(
            command_id="persistence.quicklook_generators",
            name="Quick Look Generators",
            description="Lists Quick Look generator plug-ins that can execute when previews are generated.",
            argv=["/bin/ls", "-la", "/Library/QuickLook", "~/Library/QuickLook"],
            category="Persistence",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="File names may reveal installed document-preview tooling.",
            failure_modes=["Directories may not exist.", "Permission denied."],
            user_disclaimer="Read-only listing of Quick Look plug-in locations.",
            safer_alternative="Inspect Quick Look folders manually.",
        ),
        _command(
            command_id="persistence.login_hooks",
            name="Login And Logout Hooks",
            description="Reads deprecated loginwindow hook preferences if present.",
            argv=["/usr/bin/defaults", "read", "/Library/Preferences/com.apple.loginwindow"],
            category="Persistence",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="May expose login-window configuration values.",
            failure_modes=["Preference file or keys may be absent.", "defaults unavailable."],
            user_disclaimer="Read-only loginwindow preference inspection.",
            safer_alternative="Inspect loginwindow preferences manually.",
        ),
        _command(
            command_id="persistence.native_messaging_hosts",
            name="Browser Native Messaging Hosts",
            description="Lists browser native messaging host locations used to bridge browsers to local programs.",
            argv=[
                "/bin/ls",
                "-la",
                "/Library/Google/Chrome/NativeMessagingHosts",
                "~/Library/Application Support/Google/Chrome/NativeMessagingHosts",
                "/Library/Application Support/Mozilla/NativeMessagingHosts",
                "~/Library/Application Support/Mozilla/NativeMessagingHosts",
            ],
            category="Persistence",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="File names may reveal browser integrations and local app bridges.",
            failure_modes=["Directories may not exist.", "Permission denied.", "Browser paths vary by channel."],
            user_disclaimer="Read-only native messaging host listing.",
            safer_alternative="Review browser extension and native messaging settings manually.",
        ),
        _command(
            command_id="network.listening_ports",
            name="Listening Ports",
            description="Lists listening TCP sockets with process names.",
            argv=["/usr/sbin/lsof", "-nP", "-iTCP", "-sTCP:LISTEN"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal process names and local services.",
            failure_modes=["lsof unavailable.", "Partial output due to permissions."],
            user_disclaimer="Read-only network metadata inspection.",
            safer_alternative="Inspect network listeners with Activity Monitor.",
        ),
        _command(
            command_id="network.active_connections",
            name="Active Connections",
            description="Lists active local network connections.",
            argv=["/usr/sbin/netstat", "-an"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal active local and remote connection endpoints.",
            failure_modes=["netstat unavailable.", "Large output may be truncated."],
            user_disclaimer="Read-only network metadata inspection.",
            safer_alternative="Inspect connections in Activity Monitor.",
        ),
        _command(
            command_id="network.dns_settings",
            name="DNS Settings",
            description="Shows current DNS resolver configuration.",
            argv=["/usr/sbin/scutil", "--dns"],
            category="Network",
            risk_level="safe",
            timeout_seconds=10,
            collection_warning="May reveal internal DNS domains or resolvers.",
            failure_modes=["scutil unavailable.", "Output can be verbose."],
            user_disclaimer="Read-only DNS inspection.",
            safer_alternative="Review DNS settings in System Settings.",
        ),
        _command(
            command_id="network.proxy_settings",
            name="Proxy Settings",
            description="Reads current Wi-Fi proxy settings.",
            argv=["/usr/sbin/networksetup", "-getwebproxy", "Wi-Fi"],
            category="Network",
            risk_level="safe",
            timeout_seconds=10,
            collection_warning="May reveal internal proxy hosts.",
            failure_modes=["networksetup unavailable.", "The active network service may not be named Wi-Fi."],
            user_disclaimer="Read-only proxy inspection.",
            safer_alternative="Review proxy settings in System Settings.",
        ),
        _command(
            command_id="network.remote_login",
            name="Remote Login Status",
            description="Reads SSH remote login status.",
            argv=["/usr/sbin/systemsetup", "-getremotelogin"],
            category="Network",
            risk_level="safe",
            timeout_seconds=10,
            collection_warning="No sensitive content expected.",
            failure_modes=["systemsetup unavailable.", "May require admin on some systems."],
            user_disclaimer="Read-only remote login status inspection.",
            safer_alternative="Review Sharing settings in System Settings.",
        ),
        _command(
            command_id="network.screen_sharing",
            name="Screen Sharing Status",
            description="Reads screen sharing launchd state.",
            argv=["/bin/launchctl", "print-disabled", "system"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal disabled/enabled system services.",
            failure_modes=["launchctl unavailable.", "Output can be verbose."],
            user_disclaimer="Read-only service state inspection.",
            safer_alternative="Review Sharing settings in System Settings.",
        ),
        _command(
            command_id="network.routing_table",
            name="Routing Table",
            description="Shows current route table for unexpected gateways or tunnels.",
            argv=["/usr/sbin/netstat", "-rn"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal local network ranges, gateways, and VPN routes.",
            failure_modes=["netstat unavailable.", "Output can be verbose on VPN-heavy systems."],
            user_disclaimer="Read-only route metadata inspection.",
            safer_alternative="Review active network services in System Settings.",
        ),
        _command(
            command_id="network.interfaces",
            name="Network Interfaces",
            description="Lists network interfaces and link state.",
            argv=["/sbin/ifconfig", "-a"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal MAC addresses, local IP addresses, and interface names.",
            failure_modes=["ifconfig unavailable.", "Output can be verbose."],
            user_disclaimer="Read-only interface metadata inspection.",
            safer_alternative="Review network interfaces in System Settings.",
        ),
        _command(
            command_id="network.arp_cache",
            name="ARP Cache",
            description="Lists observed local network neighbors from the ARP cache.",
            argv=["/usr/sbin/arp", "-an"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal local network device addresses.",
            failure_modes=["arp unavailable.", "Cache may be empty or stale."],
            user_disclaimer="Read-only ARP cache inspection.",
            safer_alternative="Inspect local network devices through router or network tools.",
        ),
        _command(
            command_id="network.vpn_services",
            name="Network Service Order",
            description="Lists configured network services, including VPN-style services when present.",
            argv=["/usr/sbin/networksetup", "-listallnetworkservices"],
            category="Network",
            risk_level="safe",
            timeout_seconds=10,
            collection_warning="May reveal configured network service names.",
            failure_modes=["networksetup unavailable.", "Managed profiles may hide details."],
            user_disclaimer="Read-only network service listing.",
            safer_alternative="Review Network settings manually.",
        ),
        _command(
            command_id="network.wifi_power",
            name="Wi-Fi Power State",
            description="Reads Wi-Fi power state for the primary Wi-Fi interface.",
            argv=["/usr/sbin/networksetup", "-getairportpower", "en0"],
            category="Network",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected beyond interface power state.",
            failure_modes=["Wi-Fi interface may not be en0.", "networksetup unavailable."],
            user_disclaimer="Read-only Wi-Fi state inspection.",
            safer_alternative="Review Wi-Fi status in Control Center or System Settings.",
        ),
        _command(
            command_id="accounts.admin_users",
            name="Admin Users",
            description="Lists local users in the admin group.",
            argv=["/usr/bin/dscl", ".", "-read", "/Groups/admin", "GroupMembership"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="Exposes account names with admin rights.",
            failure_modes=["dscl unavailable.", "Directory Services errors."],
            user_disclaimer="Read-only group membership inspection.",
            safer_alternative="Review users in System Settings.",
        ),
        _command(
            command_id="accounts.hidden_users",
            name="Hidden Users",
            description="Lists hidden login-window users.",
            argv=["/usr/bin/defaults", "read", "/Library/Preferences/com.apple.loginwindow", "HiddenUsersList"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="Exposes hidden account names if configured.",
            failure_modes=["Preference key missing.", "defaults unavailable."],
            user_disclaimer="Read-only preference inspection.",
            safer_alternative="Inspect login window settings manually.",
        ),
        _command(
            command_id="accounts.local_users",
            name="Local User Records",
            description="Reads local user account records from Directory Services.",
            argv=["/usr/bin/dscl", ".", "-readall", "/Users", "RecordName", "UniqueID", "PrimaryGroupID", "NFSHomeDirectory", "UserShell"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=15,
            collection_warning="Exposes local account names, home directories, and shells.",
            failure_modes=["dscl unavailable.", "Large output on managed systems."],
            user_disclaimer="Read-only Directory Services query.",
            safer_alternative="Inspect users via System Settings and `dscl` manually.",
        ),
        _command(
            command_id="accounts.login_history",
            name="Login History",
            description="Reads the most recent local login history entries.",
            argv=["/usr/bin/last", "-10"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="Exposes recent account and terminal history.",
            failure_modes=["last unavailable.", "No history available."],
            user_disclaimer="Read-only login history inspection.",
            safer_alternative="Inspect login logs manually.",
        ),
        _command(
            command_id="accounts.uid_zero_users",
            name="UID 0 Account Records",
            description="Lists local Directory Services records with UID 0 fields for root-equivalent account review.",
            argv=["/usr/bin/dscl", ".", "-search", "/Users", "UniqueID", "0"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May expose privileged account record names.",
            failure_modes=["dscl unavailable.", "Directory Services errors."],
            user_disclaimer="Read-only UID search.",
            safer_alternative="Review privileged accounts manually with Directory Utility or dscl.",
        ),
        _command(
            command_id="accounts.sudoers_includes",
            name="Sudoers Includes",
            description="Lists sudoers include directory entries for unexpected privilege grants.",
            argv=["/bin/ls", "-la", "/etc/sudoers.d", "/private/etc/sudoers.d"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="File names may reveal local privilege-management policy.",
            failure_modes=["Directories may not exist.", "Permission denied."],
            user_disclaimer="Read-only sudoers include listing; sudo policy is not changed.",
            safer_alternative="Review sudoers policy manually with administrator approval.",
        ),
        _command(
            command_id="accounts.ssh_authorized_keys_locations",
            name="SSH Authorized Keys Locations",
            description="Finds authorized_keys file locations without reading key contents.",
            argv=["/usr/bin/find", "/Users", "-maxdepth", "4", "-name", "authorized_keys", "-type", "f", "-print"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=15,
            collection_warning="May reveal user home paths and SSH access configuration locations.",
            failure_modes=["Permission denied for some homes.", "Large user directories can slow the scan."],
            user_disclaimer="Read-only path discovery; key material is not printed.",
            safer_alternative="Inspect each user's .ssh directory manually.",
        ),
        _command(
            command_id="accounts.shells",
            name="Allowed Login Shells",
            description="Reads the system list of allowed login shells.",
            argv=["/bin/cat", "/etc/shells"],
            category="Accounts & Privileges",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["File unavailable.", "Permission denied."],
            user_disclaimer="Read-only shells file inspection.",
            safer_alternative="Inspect /etc/shells manually.",
        ),
        _command(
            command_id="files.running_processes",
            name="Running Processes",
            description="Lists active processes with owning user and path.",
            argv=["/bin/ps", "-axo", "user=,pid=,ppid=,comm=,args="],
            category="Files & Processes",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="Exposes process paths and account names.",
            failure_modes=["ps unavailable.", "Output can be large."],
            user_disclaimer="Read-only process inspection.",
            safer_alternative="Use Activity Monitor.",
        ),
        _command(
            command_id="files.writable_exec_locations",
            name="Executable Files In Shared Temp Paths",
            description="Finds executable files in shared writable locations often used for staging.",
            argv=["/usr/bin/find", "/tmp", "/var/tmp", "/private/tmp", "/Users/Shared", "-maxdepth", "3", "-type", "f", "-perm", "-111", "-print"],
            category="Files & Processes",
            risk_level="sensitive",
            timeout_seconds=20,
            collection_warning="May reveal file names in shared temporary locations.",
            failure_modes=["Permission denied.", "Large temporary directories can slow the scan."],
            user_disclaimer="Read-only path discovery; files are not opened or executed.",
            safer_alternative="Inspect shared temporary paths manually.",
        ),
        _command(
            command_id="files.recent_tmp_changes",
            name="Recent Shared Temp Changes",
            description="Lists recently changed files in shared temporary locations for staging review.",
            argv=["/usr/bin/find", "/tmp", "/var/tmp", "/private/tmp", "/Users/Shared", "-maxdepth", "3", "-mtime", "-2", "-print"],
            category="Files & Processes",
            risk_level="sensitive",
            timeout_seconds=20,
            collection_warning="May reveal file and directory names in shared temporary locations.",
            failure_modes=["Permission denied.", "Large temporary directories can slow the scan."],
            user_disclaimer="Read-only path discovery; file contents are not read.",
            safer_alternative="Inspect shared temporary paths manually.",
        ),
        _command(
            command_id="files.quarantine_recent_downloads",
            name="Recent Quarantine Flags",
            description="Lists recent downloaded files that carry quarantine metadata.",
            argv=["/usr/bin/find", "~/Downloads", "-maxdepth", "2", "-mtime", "-14", "-type", "f", "-print"],
            category="Files & Processes",
            risk_level="sensitive",
            timeout_seconds=15,
            collection_warning="May reveal names of recently downloaded files.",
            failure_modes=["Downloads directory may not exist.", "Permission denied."],
            user_disclaimer="Read-only path listing; file contents and browser history are not inspected.",
            safer_alternative="Review recent downloads manually in Finder.",
        ),
        _command(
            command_id="files.open_files_by_network_processes",
            name="Open Files For Network Processes",
            description="Lists open files and sockets to correlate active network programs with file paths.",
            argv=["/usr/sbin/lsof", "-nP", "-i"],
            category="Files & Processes",
            risk_level="sensitive",
            timeout_seconds=15,
            collection_warning="May reveal process names, open network endpoints, and file paths.",
            failure_modes=["lsof unavailable.", "Partial output due to permissions.", "Output can be large."],
            user_disclaimer="Read-only process/file/socket metadata inspection.",
            safer_alternative="Use Activity Monitor and Network tab manually.",
        ),
        _command(
            command_id="extensions.system_extensions",
            name="System Extensions",
            description="Lists installed System Extensions used by endpoint, network, and driver software.",
            argv=["/usr/bin/systemextensionsctl", "list"],
            category="Extensions & Drivers",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal installed endpoint security, network, or driver products.",
            failure_modes=["systemextensionsctl unavailable on older macOS.", "Output varies by macOS version."],
            user_disclaimer="Read-only System Extension listing.",
            safer_alternative="Review Extensions and Login Items in System Settings.",
        ),
        _command(
            command_id="extensions.loaded_kernel_extensions",
            name="Loaded Kernel Extensions",
            description="Lists loaded kernel extensions for legacy driver and rootkit-style persistence review.",
            argv=["/usr/bin/kmutil", "showloaded"],
            category="Extensions & Drivers",
            risk_level="sensitive",
            timeout_seconds=15,
            collection_warning="May reveal installed security, virtualization, and driver software.",
            failure_modes=["kmutil unavailable.", "Partial data on some macOS versions."],
            user_disclaimer="Read-only loaded-extension inspection.",
            safer_alternative="Review installed extensions in System Information.",
        ),
        _command(
            command_id="extensions.audio_units",
            name="Audio Units",
            description="Lists Audio Unit plug-in locations that can load into audio workflows.",
            argv=["/bin/ls", "-la", "/Library/Audio/Plug-Ins/Components", "~/Library/Audio/Plug-Ins/Components"],
            category="Extensions & Drivers",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="File names may reveal installed audio software.",
            failure_modes=["Directories may not exist.", "Permission denied."],
            user_disclaimer="Read-only plug-in location listing.",
            safer_alternative="Inspect Audio plug-in folders manually.",
        ),
        _command(
            command_id="extensions.internet_plugins",
            name="Internet Plug-Ins",
            description="Lists legacy Internet Plug-Ins locations.",
            argv=["/bin/ls", "-la", "/Library/Internet Plug-Ins", "~/Library/Internet Plug-Ins"],
            category="Extensions & Drivers",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="File names may reveal installed browser plug-ins.",
            failure_modes=["Directories may not exist.", "Permission denied."],
            user_disclaimer="Read-only plug-in location listing.",
            safer_alternative="Inspect Internet Plug-Ins folders manually.",
        ),
        _command(
            command_id="browser.safari_extensions",
            name="Safari Extension Locations",
            description="Lists Safari extension storage locations without reading browsing data.",
            argv=["/bin/ls", "-la", "~/Library/Safari/Extensions", "~/Library/Containers/com.apple.Safari/Data/Library/Safari/Extensions"],
            category="Browser Security",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="May reveal installed extension names; browsing history is not inspected.",
            failure_modes=["Directories may not exist.", "Permission denied.", "Safari storage paths vary by version."],
            user_disclaimer="Read-only extension location listing; history, cookies, and tabs are not accessed.",
            safer_alternative="Review Safari Extensions in Safari Settings.",
        ),
        _command(
            command_id="browser.chrome_extensions",
            name="Chromium Extension Locations",
            description="Lists common Chromium extension directories without reading browser history.",
            argv=["/bin/ls", "-la", "~/Library/Application Support/Google/Chrome/Default/Extensions", "~/Library/Application Support/Chromium/Default/Extensions"],
            category="Browser Security",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="May reveal installed extension IDs; browsing history is not inspected.",
            failure_modes=["Directories may not exist.", "Permission denied.", "Profiles may use non-default names."],
            user_disclaimer="Read-only extension directory listing.",
            safer_alternative="Review browser extensions inside the browser UI.",
        ),
        _command(
            command_id="security.tcc_user_database",
            name="User Privacy Permission Database",
            description="Lists the user TCC database location for privacy-permission review without dumping contents.",
            argv=["/bin/ls", "-la", "~/Library/Application Support/com.apple.TCC"],
            category="Privacy Permissions",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="May reveal privacy-permission database file metadata.",
            failure_modes=["Directory may not exist.", "Permission denied."],
            user_disclaimer="Read-only metadata listing; private permission records are not dumped.",
            safer_alternative="Review Privacy & Security permissions in System Settings.",
        ),
        _command(
            command_id="security.tcc_system_database",
            name="System Privacy Permission Database",
            description="Lists the system TCC database location for managed privacy-permission review.",
            argv=["/bin/ls", "-la", "/Library/Application Support/com.apple.TCC"],
            category="Privacy Permissions",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="May reveal system privacy-permission database file metadata.",
            failure_modes=["Directory may not exist.", "Permission denied."],
            user_disclaimer="Read-only metadata listing; private permission records are not dumped.",
            safer_alternative="Review managed privacy permissions in System Settings or MDM.",
        ),
        _command(
            command_id="security.configuration_profiles",
            name="Configuration Profiles",
            description="Lists installed configuration profiles that may control security, network, or privacy settings.",
            argv=["/usr/bin/profiles", "list"],
            category="Policy & Management",
            risk_level="sensitive",
            timeout_seconds=15,
            collection_warning="May reveal organization, MDM, VPN, certificate, or policy profile names.",
            failure_modes=["profiles unavailable.", "Managed systems may restrict output."],
            user_disclaimer="Read-only profile listing.",
            safer_alternative="Review Profiles in System Settings or with the managing organization.",
        ),
        _command(
            command_id="security.mdm_enrollment",
            name="MDM Enrollment Status",
            description="Shows whether the Mac reports MDM enrollment.",
            argv=["/usr/bin/profiles", "status", "-type", "enrollment"],
            category="Policy & Management",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal device management enrollment state.",
            failure_modes=["profiles unavailable.", "Output varies by macOS version."],
            user_disclaimer="Read-only enrollment status inspection.",
            safer_alternative="Review device management status in System Settings.",
        ),
        _command(
            command_id="security.certificates_system_keychain",
            name="System Keychain Certificates",
            description="Lists certificate identities in the system keychain for unexpected trust anchors.",
            argv=["/usr/bin/security", "find-certificate", "-a", "-Z", "/Library/Keychains/System.keychain"],
            category="Policy & Management",
            risk_level="sensitive",
            timeout_seconds=15,
            collection_warning="May reveal certificate subjects and fingerprints; private keys are not exported.",
            failure_modes=["security command unavailable.", "Permission or keychain errors."],
            user_disclaimer="Read-only certificate metadata listing.",
            safer_alternative="Review System keychain certificates in Keychain Access.",
        ),
        _command(
            command_id="security.xprotect_version",
            name="XProtect Version",
            description="Reads XProtect bundle version metadata.",
            argv=["/usr/bin/defaults", "read", "/Library/Apple/System/Library/CoreServices/XProtect.bundle/Contents/Info", "CFBundleShortVersionString"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["Path may vary by macOS version.", "defaults unavailable."],
            user_disclaimer="Read-only XProtect version inspection.",
            safer_alternative="Review system security update status in System Settings.",
        ),
        _command(
            command_id="security.xprotect_remediator",
            name="XProtect Remediator Version",
            description="Reads XProtect Remediator version metadata when installed.",
            argv=["/usr/bin/defaults", "read", "/Library/Apple/System/Library/CoreServices/XProtect.app/Contents/Info", "CFBundleShortVersionString"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["Path may vary by macOS version.", "defaults unavailable."],
            user_disclaimer="Read-only XProtect Remediator version inspection.",
            safer_alternative="Review system security update status in System Settings.",
        ),
        _command(
            command_id="security.mrt_version",
            name="Malware Removal Tool Version",
            description="Reads MRT version metadata when present.",
            argv=["/usr/bin/defaults", "read", "/Library/Apple/System/Library/CoreServices/MRT.app/Contents/Info", "CFBundleShortVersionString"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["MRT path may not exist on newer macOS.", "defaults unavailable."],
            user_disclaimer="Read-only MRT version inspection.",
            safer_alternative="Review system security update status in System Settings.",
        ),
        _command(
            command_id="security.firewall_stealth",
            name="Firewall Stealth Mode",
            description="Checks application firewall stealth mode state.",
            argv=["/usr/libexec/ApplicationFirewall/socketfilterfw", "--getstealthmode"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["Command unavailable.", "Permission errors."],
            user_disclaimer="Read-only firewall stealth-mode inspection.",
            safer_alternative="Review firewall options in System Settings.",
        ),
        _command(
            command_id="security.lockdown_status",
            name="Lockdown Mode Preference",
            description="Reads Lockdown Mode preference state when exposed by macOS preferences.",
            argv=["/usr/bin/defaults", "read", "com.apple.Safari", "LockdownModeEnabled"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="May not reflect every Lockdown Mode state source on all macOS versions.",
            failure_modes=["Preference key may be absent.", "defaults unavailable.", "macOS version may store state elsewhere."],
            user_disclaimer="Read-only preference inspection.",
            safer_alternative="Review Lockdown Mode manually in System Settings.",
        ),
        _command(
            command_id="security.sip_status",
            name="SIP Status",
            description="Checks System Integrity Protection status.",
            argv=["/usr/bin/csrutil", "status"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["csrutil unavailable outside recovery on some systems."],
            user_disclaimer="Read-only SIP status inspection.",
            safer_alternative="Check SIP via Recovery if needed.",
        ),
        _command(
            command_id="security.gatekeeper",
            name="Gatekeeper Status",
            description="Checks Gatekeeper assessment status.",
            argv=["/usr/sbin/spctl", "--status"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["spctl unavailable."],
            user_disclaimer="Read-only Gatekeeper status inspection.",
            safer_alternative="Review Gatekeeper in System Settings.",
        ),
        _command(
            command_id="security.filevault",
            name="FileVault Status",
            description="Checks FileVault encryption status.",
            argv=["/usr/bin/fdesetup", "status"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="May disclose whether disk encryption is enabled.",
            failure_modes=["fdesetup unavailable.", "Privilege prompts on some systems."],
            user_disclaimer="Read-only FileVault status inspection.",
            safer_alternative="Review FileVault in System Settings.",
        ),
        _command(
            command_id="security.firewall_status",
            name="Firewall Status",
            description="Checks application firewall global state.",
            argv=["/usr/libexec/ApplicationFirewall/socketfilterfw", "--getglobalstate"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["Command unavailable.", "Permission errors."],
            user_disclaimer="Read-only firewall status inspection.",
            safer_alternative="Review firewall settings in System Settings.",
        ),
        _command(
            command_id="security.auto_updates",
            name="Automatic Updates",
            description="Reads software update automatic check settings.",
            argv=["/usr/bin/defaults", "read", "/Library/Preferences/com.apple.SoftwareUpdate", "AutomaticCheckEnabled"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["Preference key missing.", "defaults unavailable."],
            user_disclaimer="Read-only software update preference inspection.",
            safer_alternative="Review Software Update settings in System Settings.",
        ),
    ]
    return {command.id: command for command in commands}
