from __future__ import annotations

from mac_audit_agent.models import AuditCommand


def _command(
    *,
    command_id: str,
    name: str,
    description: str,
    argv: list[str],
    category: str,
    risk_level: str = "safe",
    timeout_seconds: int = 10,
    collection_warning: str,
    failure_modes: list[str],
    user_disclaimer: str,
    safer_alternative: str,
) -> AuditCommand:
    return AuditCommand(
        id=command_id,
        name=name,
        description=description,
        command=argv,
        privilege_required=False,
        risk_level=risk_level,  # type: ignore[arg-type]
        mutates_system=False,
        timeout_seconds=timeout_seconds,
        collection_warning=collection_warning,
        failure_modes=failure_modes,
        user_disclaimer=user_disclaimer,
        safer_alternative=safer_alternative,
        category=category,
    )


def build_command_registry() -> dict[str, AuditCommand]:
    commands = [
        _command(
            command_id="persistence.user_launch_agents",
            name="User LaunchAgents",
            description="Lists per-user LaunchAgents that run at login.",
            argv=["/bin/ls", "-la", "~/Library/LaunchAgents"],
            category="Persistence",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="File names may reveal installed software or management tooling.",
            failure_modes=["Directory does not exist.", "Permission denied."],
            user_disclaimer="Read-only listing only; no plist contents are modified.",
            safer_alternative="Inspect the directory manually in Finder.",
        ),
        _command(
            command_id="persistence.system_launch_agents",
            name="System LaunchAgents",
            description="Lists system LaunchAgents.",
            argv=["/bin/ls", "-la", "/Library/LaunchAgents"],
            category="Persistence",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="File names may reveal installed software or management tooling.",
            failure_modes=["Directory does not exist.", "Permission denied."],
            user_disclaimer="Read-only listing only.",
            safer_alternative="Inspect the directory manually in Finder.",
        ),
        _command(
            command_id="persistence.system_launch_daemons",
            name="System LaunchDaemons",
            description="Lists system LaunchDaemons.",
            argv=["/bin/ls", "-la", "/Library/LaunchDaemons"],
            category="Persistence",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="File names may reveal installed software or management tooling.",
            failure_modes=["Directory does not exist.", "Permission denied."],
            user_disclaimer="Read-only listing only.",
            safer_alternative="Inspect the directory manually in Finder.",
        ),
        _command(
            command_id="persistence.login_items",
            name="Login Items",
            description="Reads configured login items via System Events.",
            argv=["/usr/bin/osascript", "-e", 'tell application "System Events" to get the name of every login item'],
            category="Persistence",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="App names configured for login may be sensitive.",
            failure_modes=["Automation permission denied.", "System Events unavailable."],
            user_disclaimer="Read-only query of configured login item names.",
            safer_alternative="Review Login Items in System Settings.",
        ),
        _command(
            command_id="network.listening_ports",
            name="Listening Ports",
            description="Lists listening TCP sockets with process names.",
            argv=["/usr/sbin/lsof", "-nP", "-iTCP", "-sTCP:LISTEN"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal process names and local services.",
            failure_modes=["lsof unavailable.", "Partial output due to permissions."],
            user_disclaimer="Read-only network metadata inspection.",
            safer_alternative="Inspect network listeners with Activity Monitor.",
        ),
        _command(
            command_id="network.active_connections",
            name="Active Connections",
            description="Lists active local network connections.",
            argv=["/usr/sbin/netstat", "-an"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal active local and remote connection endpoints.",
            failure_modes=["netstat unavailable.", "Large output may be truncated."],
            user_disclaimer="Read-only network metadata inspection.",
            safer_alternative="Inspect connections in Activity Monitor.",
        ),
        _command(
            command_id="network.dns_settings",
            name="DNS Settings",
            description="Shows current DNS resolver configuration.",
            argv=["/usr/sbin/scutil", "--dns"],
            category="Network",
            risk_level="safe",
            timeout_seconds=10,
            collection_warning="May reveal internal DNS domains or resolvers.",
            failure_modes=["scutil unavailable.", "Output can be verbose."],
            user_disclaimer="Read-only DNS inspection.",
            safer_alternative="Review DNS settings in System Settings.",
        ),
        _command(
            command_id="network.proxy_settings",
            name="Proxy Settings",
            description="Reads current Wi-Fi proxy settings.",
            argv=["/usr/sbin/networksetup", "-getwebproxy", "Wi-Fi"],
            category="Network",
            risk_level="safe",
            timeout_seconds=10,
            collection_warning="May reveal internal proxy hosts.",
            failure_modes=["networksetup unavailable.", "The active network service may not be named Wi-Fi."],
            user_disclaimer="Read-only proxy inspection.",
            safer_alternative="Review proxy settings in System Settings.",
        ),
        _command(
            command_id="network.remote_login",
            name="Remote Login Status",
            description="Reads SSH remote login status.",
            argv=["/usr/sbin/systemsetup", "-getremotelogin"],
            category="Network",
            risk_level="safe",
            timeout_seconds=10,
            collection_warning="No sensitive content expected.",
            failure_modes=["systemsetup unavailable.", "May require admin on some systems."],
            user_disclaimer="Read-only remote login status inspection.",
            safer_alternative="Review Sharing settings in System Settings.",
        ),
        _command(
            command_id="network.screen_sharing",
            name="Screen Sharing Status",
            description="Reads screen sharing launchd state.",
            argv=["/bin/launchctl", "print-disabled", "system"],
            category="Network",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="May reveal disabled/enabled system services.",
            failure_modes=["launchctl unavailable.", "Output can be verbose."],
            user_disclaimer="Read-only service state inspection.",
            safer_alternative="Review Sharing settings in System Settings.",
        ),
        _command(
            command_id="accounts.admin_users",
            name="Admin Users",
            description="Lists local users in the admin group.",
            argv=["/usr/bin/dscl", ".", "-read", "/Groups/admin", "GroupMembership"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="Exposes account names with admin rights.",
            failure_modes=["dscl unavailable.", "Directory Services errors."],
            user_disclaimer="Read-only group membership inspection.",
            safer_alternative="Review users in System Settings.",
        ),
        _command(
            command_id="accounts.hidden_users",
            name="Hidden Users",
            description="Lists hidden login-window users.",
            argv=["/usr/bin/defaults", "read", "/Library/Preferences/com.apple.loginwindow", "HiddenUsersList"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=5,
            collection_warning="Exposes hidden account names if configured.",
            failure_modes=["Preference key missing.", "defaults unavailable."],
            user_disclaimer="Read-only preference inspection.",
            safer_alternative="Inspect login window settings manually.",
        ),
        _command(
            command_id="accounts.local_users",
            name="Local User Records",
            description="Reads local user account records from Directory Services.",
            argv=["/usr/bin/dscl", ".", "-readall", "/Users", "RecordName", "UniqueID", "PrimaryGroupID", "NFSHomeDirectory", "UserShell"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=15,
            collection_warning="Exposes local account names, home directories, and shells.",
            failure_modes=["dscl unavailable.", "Large output on managed systems."],
            user_disclaimer="Read-only Directory Services query.",
            safer_alternative="Inspect users via System Settings and `dscl` manually.",
        ),
        _command(
            command_id="accounts.login_history",
            name="Login History",
            description="Reads the most recent local login history entries.",
            argv=["/usr/bin/last", "-10"],
            category="Accounts & Privileges",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="Exposes recent account and terminal history.",
            failure_modes=["last unavailable.", "No history available."],
            user_disclaimer="Read-only login history inspection.",
            safer_alternative="Inspect login logs manually.",
        ),
        _command(
            command_id="files.running_processes",
            name="Running Processes",
            description="Lists active processes with owning user and path.",
            argv=["/bin/ps", "-axo", "user=,pid=,ppid=,comm=,args="],
            category="Files & Processes",
            risk_level="sensitive",
            timeout_seconds=10,
            collection_warning="Exposes process paths and account names.",
            failure_modes=["ps unavailable.", "Output can be large."],
            user_disclaimer="Read-only process inspection.",
            safer_alternative="Use Activity Monitor.",
        ),
        _command(
            command_id="security.sip_status",
            name="SIP Status",
            description="Checks System Integrity Protection status.",
            argv=["/usr/bin/csrutil", "status"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["csrutil unavailable outside recovery on some systems."],
            user_disclaimer="Read-only SIP status inspection.",
            safer_alternative="Check SIP via Recovery if needed.",
        ),
        _command(
            command_id="security.gatekeeper",
            name="Gatekeeper Status",
            description="Checks Gatekeeper assessment status.",
            argv=["/usr/sbin/spctl", "--status"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["spctl unavailable."],
            user_disclaimer="Read-only Gatekeeper status inspection.",
            safer_alternative="Review Gatekeeper in System Settings.",
        ),
        _command(
            command_id="security.filevault",
            name="FileVault Status",
            description="Checks FileVault encryption status.",
            argv=["/usr/bin/fdesetup", "status"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="May disclose whether disk encryption is enabled.",
            failure_modes=["fdesetup unavailable.", "Privilege prompts on some systems."],
            user_disclaimer="Read-only FileVault status inspection.",
            safer_alternative="Review FileVault in System Settings.",
        ),
        _command(
            command_id="security.firewall_status",
            name="Firewall Status",
            description="Checks application firewall global state.",
            argv=["/usr/libexec/ApplicationFirewall/socketfilterfw", "--getglobalstate"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["Command unavailable.", "Permission errors."],
            user_disclaimer="Read-only firewall status inspection.",
            safer_alternative="Review firewall settings in System Settings.",
        ),
        _command(
            command_id="security.auto_updates",
            name="Automatic Updates",
            description="Reads software update automatic check settings.",
            argv=["/usr/bin/defaults", "read", "/Library/Preferences/com.apple.SoftwareUpdate", "AutomaticCheckEnabled"],
            category="macOS Security",
            risk_level="safe",
            timeout_seconds=5,
            collection_warning="No sensitive content expected.",
            failure_modes=["Preference key missing.", "defaults unavailable."],
            user_disclaimer="Read-only software update preference inspection.",
            safer_alternative="Review Software Update settings in System Settings.",
        ),
    ]
    return {command.id: command for command in commands}
