from __future__ import annotations

from mac_audit_agent.quality.audit_models import FunctionalCheck


FEATURES: list[tuple[str, str, str, str, str]] = [
    ("core.app_startup", "Core", "app startup", "Application modules import and main UI can be constructed.", "critical"),
    ("core.database_rw", "Core", "database open/read/write", "SQLite database opens and background state can be written and read.", "blocker"),
    ("core.settings_load_save", "Core", "settings load/save", "MonitorSettings defaults, save, reload, and versioning work.", "blocker"),
    ("core.assessment_builder", "Core", "assessment builder", "Security assessment builds from real local data structures.", "high"),
    ("core.report_storage", "Core", "report storage", "Report directory is writable.", "high"),
    ("scan.safe_scan", "Scans", "Safe Scan", "Safe scan can run without destructive actions.", "critical"),
    ("scan.localhost_ports", "Scans", "localhost port scan", "Port parser returns structured listening/connection data or explicit unavailable reason.", "high"),
    ("scan.network", "Scans", "network scan", "Network collection returns structured data or exact failure.", "high"),
    ("scan.admin_persistence", "Scans", "admin/persistence scan", "LaunchAgents, LaunchDaemons, admin users, and sudoers are handled safely.", "high"),
    ("persistence.registry", "Persistence Intelligence", "scanner registry loads", "Persistence scanner registry is explicit and loadable.", "blocker"),
    ("persistence.launchd_scanner", "Persistence Intelligence", "launchd scanner works", "LaunchAgents and LaunchDaemons are parsed safely.", "critical"),
    ("persistence.workflow", "Persistence Intelligence", "scan/baseline/timeline/chain/report workflow", "Persistence workflow produces scan report, baseline comparison, timeline, chain view, and JSON report.", "blocker"),
    ("persistence.safety", "Persistence Intelligence", "safe read-only defaults", "No destructive persistence remediation actions are exposed.", "blocker"),
    ("rootkit.system_integrity_posture", "Rootkit Detection", "system integrity posture", "SIP/SSV/Gatekeeper/FileVault posture collector works or returns explicit unavailable reasons.", "high"),
    ("rootkit.extension_inventory", "Rootkit Detection", "extension inventory", "Kernel/system extension inventory works or returns explicit unavailable reasons.", "high"),
    ("rootkit.port_visibility", "Rootkit Detection", "port visibility", "lsof/netstat/local comparison works or returns explicit unavailable reasons.", "high"),
    ("rootkit.visibility_crosscheck", "Rootkit Detection", "visibility crosscheck", "Mismatch engine produces structured output.", "medium"),
    ("rootkit.persistence_correlation", "Rootkit Detection", "persistence correlation", "Correlation engine runs on sample/local data.", "high"),
    ("rootkit.report_export", "Rootkit Detection", "report export", "Rootkit suspect report exports JSON/HTML.", "high"),
    ("rootkit.no_destructive_actions", "Rootkit Detection", "no destructive actions", "No unload/delete/kill/remediate actions are exposed by default.", "blocker"),
    ("rootkit.alert_templates", "Rootkit Detection", "alert templates", "Rootkit suspect alert templates exist.", "medium"),
    ("network_intelligence.collectors", "Network Intelligence", "collector normalization", "Network Sentinel collector logic normalizes into MSAA models.", "high"),
    ("network_intelligence.storage_events", "Network Intelligence", "storage and event routing", "Network Intelligence snapshots write to MSAA DB and findings become monitor events.", "high"),
    ("network_intelligence.reports", "Network Intelligence", "report payload", "Network Intelligence data appears in MSAA report payloads.", "medium"),
    ("network_intelligence.no_standalone_runtime", "Network Intelligence", "no standalone Sentinel runtime", "MSAA does not run the old Sentinel app, CLI, or database.", "blocker"),
    ("scan.physical_devices", "Scans", "physical devices scan", "USB/Bluetooth inventory is parsed or permissions failure is explicit.", "high"),
    ("scan.apple_exposure", "Scans", "Apple Exposure Assessment", "Freshness metadata exists and stale cache is not misrepresented.", "high"),
    ("apple_exposure.update_guidance", "Scans", "Apple Exposure update guidance", "Update guidance handles structured Apple Exposure payloads without crashing.", "high"),
    ("performance.startup_lightweight", "Performance", "startup lightweight", "Startup should not force every heavy refresh.", "high"),
    ("performance.scheduler_limits", "Performance", "scheduler limits", "Scheduler enforces concurrency, cooldown, and dedupe.", "high"),
    ("performance.api_refresh_bounded", "Performance", "API refresh bounded", "API refresh has timeout/cache/backoff semantics.", "blocker"),
    ("performance.cache_resilience", "Performance", "cache resilience", "Corrupt cache must not crash lookup.", "high"),
    ("performance.subprocess_bounds", "Performance", "subprocess bounds", "Subprocess timeout and output caps are enforced.", "blocker"),
    ("performance.db_access_bounded", "Performance", "database access bounded", "Frequently queried DB fields have indexes.", "high"),
    ("performance.resource_profile_settings", "Performance", "resource profile settings", "Performance profile persists and applies.", "high"),
    ("performance.shutdown_graceful_macos_menu", "Performance", "macOS menu quit graceful", "Shutdown coordinator flushes DB and cancels work.", "medium"),
    ("performance.python_gui_runtime_guard", "Performance", "Python GUI runtime guard", "Unsupported Python GUI path is blocked before QApplication.", "blocker"),
    ("runtime.no_qt_in_headless_paths", "Runtime", "no Qt in headless paths", "Headless integrity, Pre-UAT, reports, and evidence imports do not load Qt/AppKit.", "blocker"),
    ("runtime.python_support_matrix", "Runtime", "Python support matrix", "Runtime tiers are explicit and Python 3.14 GUI is not enabled by default.", "blocker"),
    ("runtime.current_python_tier", "Runtime", "current Python tier", "The active interpreter has a classified support tier.", "blocker"),
    ("runtime.doctor_stdlib_only", "Runtime", "stdlib doctor", "Doctor boundary imports no optional GUI/native dependency.", "blocker"),
    ("runtime.gui_runtime_supported", "Runtime", "GUI runtime supported", "GUI runs only on validated Python/Qt combinations.", "blocker"),
    ("runtime.headless_commands_no_gui_import", "Runtime", "headless commands no GUI import", "Headless compatibility modules import no GUI framework.", "blocker"),
    ("runtime.optional_dependencies_classified", "Runtime", "optional dependency classification", "Optional capabilities are independently classified.", "blocker"),
    ("runtime.fallbacks_available", "Runtime", "dependency fallbacks", "Major optional dependencies have plain-language fallbacks.", "high"),
    ("runtime.no_hard_optional_imports", "Runtime", "no hard optional imports", "Headless runtime boundary uses lazy/safe dependency detection.", "blocker"),
    ("runtime.launchdaemon_python_selected", "Runtime", "LaunchDaemon Python selected", "Daemon installation selects and records a stable headless runtime.", "high"),
    ("runtime.user_notifier_python_gui_capable", "Runtime", "notifier Python GUI capable", "Notifier runtime is validated for GUI and is not Python 3.14 by default.", "blocker"),
    ("runtime.setup_guidance_available", "Runtime", "setup guidance available", "Runtime failures include exact non-destructive setup guidance.", "high"),
    ("runtime.python310_strenum_compat", "Runtime", "Python 3.10 StrEnum compatibility", "The MSAA compatibility enum preserves required string-enum behavior.", "blocker"),
    ("runtime.no_direct_stdlib_strenum_import", "Runtime", "no direct stdlib StrEnum import", "Source modules use the centralized MSAA compatibility enum.", "blocker"),
    ("runtime.startup_error_classifier_stdlib_symbol", "Runtime", "stdlib symbol startup classification", "Missing stdlib symbols are classified as Python feature gaps, not pip dependencies.", "blocker"),
    ("runtime.sudo_gui_blocked", "Runtime", "sudo GUI blocked", "Root GUI startup is blocked before application imports.", "blocker"),
    ("runtime.sudo_headless_protection_allowed", "Runtime", "sudo protection actions allowed", "Explicit root-safe protection actions route through the headless launcher.", "high"),
    ("runtime.sudo_gui_no_qt_import", "Runtime", "sudo GUI has no Qt import", "Root GUI startup is blocked before any Qt probe or import.", "blocker"),
    ("runtime.guiroot001_guidance_complete", "Runtime", "GUIROOT001 guidance complete", "Root GUI guidance includes protection, doctor, and normal-user GUI commands.", "high"),
    ("runtime.python314_not_recommended_for_gui", "Runtime", "Python 3.14 not recommended for GUI", "GUI guidance recommends only validated Python versions.", "blocker"),
    ("protection.launcher_install_handoff_available", "Active Protection", "launcher install handoff", "The root-safe launcher install path returns users to a normal-user GUI session.", "high"),
    ("runtime.launcher_imports_gui_only_after_guard", "Runtime", "launcher GUI import boundary", "The bootstrap evaluates runtime and privilege guards before GUI imports.", "blocker"),
    ("runtime.doctor_reports_feature_gap", "Runtime", "doctor Python feature reporting", "Doctor reports native and compatible Python feature availability.", "blocker"),
    ("runtime.optional_dependency_guidance_correct", "Runtime", "optional dependency guidance", "Startup guidance never recommends installing a standard-library module.", "blocker"),
    ("runtime.launcher_stage0_stdlib_only", "Runtime", "Stage-0 launcher stdlib boundary", "Top-level launcher imports only the Python standard library.", "blocker"),
    ("runtime.gui_preflight_exists", "Runtime", "macOS GUI preflight", "A fail-closed macOS GUI preflight runs before Qt startup.", "blocker"),
    ("runtime.qapplication_guarded", "Runtime", "QApplication guarded", "Every QApplication construction site has a fail-closed guard.", "blocker"),
    ("runtime.qt_smoke_probe_available", "Runtime", "isolated Qt smoke probe", "Qt imports and QApplication probing are isolated and separately controlled.", "blocker"),
    ("runtime.terminal_qt_crash_marker_handled", "Runtime", "Qt crash marker handling", "Prior runtime/mode crashes block direct GUI retry.", "blocker"),
    ("runtime.doctor_no_qt_import", "Runtime", "doctor has no Qt import", "Doctor executes without importing Qt/AppKit.", "blocker"),
    ("runtime.protection_cli_no_qt_import", "Runtime", "protection CLI has no Qt import", "Protection headless commands execute without importing Qt/AppKit.", "blocker"),
    ("runtime.startup_error_classifier_qt_appkit", "Runtime", "Qt/AppKit startup classification", "Qt/AppKit crash risk maps to GUIQT001.", "blocker"),
    ("runtime.no_misclassified_qt_crash_as_dependency", "Runtime", "Qt crash is not a dependency failure", "Qt/AppKit crash risk is never reported as DEP003.", "blocker"),
    ("runtime.python310_gui_direct_probe_safe_or_blocked", "Runtime", "Python 3.10 direct GUI policy", "Python 3.10 Terminal GUI is either independently proven safe or blocked.", "blocker"),
    ("scan.visibility_integrity", "Scans", "visibility integrity scan", "Visibility integrity check returns component statuses.", "medium"),
    ("scan.baseline_drift", "Scans", "baseline drift scan", "Baseline drift engine can compare scan state.", "medium"),
    ("daemon.user_launch_agent", "Monitor/Daemon", "user LaunchAgent status", "User monitor LaunchAgent status is inspectable.", "high"),
    ("daemon.system_launch_daemon", "Monitor/Daemon", "system LaunchDaemon status", "System LaunchDaemon status is inspectable when enabled.", "critical"),
    ("daemon.protected_monitor", "Monitor/Daemon", "protected monitor status", "Protected monitor integrity is inspectable when enabled.", "critical"),
    ("daemon.heartbeat", "Monitor/Daemon", "daemon heartbeat", "Daemon heartbeat freshness is visible.", "critical"),
    ("daemon.notifier_heartbeat", "Monitor/Daemon", "notifier heartbeat", "User notifier heartbeat and status are visible.", "blocker"),
    ("daemon.settings_version_match", "Monitor/Daemon", "settings version match", "UI/runtime settings versions are not stale.", "critical"),
    ("protection.status_resolver", "Active Protection", "structured protection status", "Live status resolves daemon, notifier, DB, alignment, heartbeat, and alerts.", "blocker"),
    ("protection.install_button_present", "Active Protection", "install action present", "Missing protection always exposes an install action.", "blocker"),
    ("protection.install_button_connected", "Active Protection", "install action connected", "Install action calls the shared headless backend.", "blocker"),
    ("protection.repair_button_connected", "Active Protection", "repair action connected", "Repair action calls the shared headless backend.", "blocker"),
    ("protection.doctor_headless_safe", "Active Protection", "doctor headless safe", "Protection CLI imports no GUI frameworks.", "blocker"),
    ("protection.system_daemon_installable", "Active Protection", "system daemon installable", "Installer produces a valid system LaunchDaemon plan/artifact.", "blocker"),
    ("protection.user_notifier_installable", "Active Protection", "user notifier installable", "Installer produces a valid notifier LaunchAgent plan/artifact.", "blocker"),
    ("protection.verify_after_install", "Active Protection", "verify after install", "Installation verification is mandatory and truthful.", "blocker"),
    ("protection.doctor_available", "Active Protection", "protection doctor available", "Headless protection doctor is callable.", "high"),
    ("protection.install_backend_available", "Active Protection", "install backend available", "Canonical installation service is callable.", "blocker"),
    ("protection.repair_backend_available", "Active Protection", "repair backend available", "Canonical repair service is callable.", "blocker"),
    ("runtime.python_gui_version_supported", "Runtime", "Python GUI runtime policy", "Python 3.14 GUI is blocked unless explicitly experimental.", "blocker"),
    ("daemon.event_db_writes", "Monitor/Daemon", "event database writes", "Monitor event database write path works.", "blocker"),
    ("alert.overlay_manager", "Alerts", "AlertOverlayManager", "Overlay manager can be initialized and reports delivery state.", "blocker"),
    ("alert.bottom_right_rendering", "Alerts", "bottom-right alert rendering", "Bottom-right alert path has render/suppression trace.", "blocker"),
    ("alert.severity_threshold", "Alerts", "severity threshold logic", "Minimum severity policy suppresses lower severity with reason.", "high"),
    ("alert.usb_path", "Alerts", "USB alert path", "USB diagnostic event policy and trace are recorded.", "high"),
    ("alert.bluetooth_path", "Alerts", "Bluetooth alert path", "Bluetooth diagnostic event policy and trace are recorded.", "high"),
    ("alert.network_path", "Alerts", "network alert path", "Network diagnostic event policy and trace are recorded.", "high"),
    ("alert.admin_path", "Alerts", "admin/persistence alert path", "Admin/persistence diagnostic event policy and trace are recorded.", "high"),
    ("alert.suppression_reasons", "Alerts", "alert suppression reasons", "Suppressed alerts include exact reason.", "critical"),
    ("alert.delivery_trace", "Alerts", "AlertDeliveryTrace", "Alert-worthy events create delivery trace.", "blocker"),
    ("settings.enforcement", "Settings", "settings enforcement", "Critical settings persist, reload, and appear in diagnostics.", "blocker"),
    ("cli.force_keyword_supported", "CLI", "force keyword supported", "Parser accepts force keyword, --force, -f, and force=true/false.", "high"),
    ("cli.force_unsupported_helpful_error", "CLI", "unsupported force error", "Unsupported force usage gives clear help.", "medium"),
    ("cli.force_safe_commands", "CLI", "safe force commands", "Force works only for approved safe retry/cache-bypass actions.", "high"),
    ("cli.force_unsafe_rejected", "CLI", "unsafe force rejected", "Unsafe force actions are blocked.", "blocker"),
    ("integrity.force_no_silent_trust", "Integrity", "force no silent trust", "Integrity verify --force does not rebaseline or trust new hashes.", "blocker"),
    ("alerts.force_no_suppression", "Alerts", "force no suppression", "Force does not suppress alerts.", "blocker"),
    ("logs.force_audit_trail", "Logs", "force audit trail", "Force actions and rejections are logged.", "high"),
    ("exports.html", "Exports", "HTML export", "HTML export creates non-empty report with limitations.", "critical"),
    ("exports.json", "Exports", "JSON export", "JSON export creates valid JSON metadata.", "critical"),
    ("exports.word", "Exports", "Word .docx export", "Word export creates readable .docx when dependency is present.", "high"),
    ("exports.excel", "Exports", "Excel .xlsx export", "Excel export creates workbook with expected sheets.", "high"),
    ("exports.assessment", "Exports", "assessment export", "Assessment HTML/JSON/Markdown exports create files.", "high"),
    ("exports.evidence_package", "Exports", "evidence package export", "Evidence package includes manifest and avoids secrets.", "medium"),
    ("framework.mapping", "Framework Mapping", "framework mapping integrity", "Framework IDs are valid and wording avoids unsupported claims.", "blocker"),
    ("remediation.recommendations_present", "Remediation", "recommendations present", "Every finding has a structured recommended fix, examination steps, and validation guidance.", "blocker"),
    ("remediation.cve_enrichment", "Remediation", "CVE/NVD enrichment", "CVE findings enrich from NVD cache/data or show an explicit unavailable state.", "critical"),
    ("remediation.cisa_kev_priority", "Remediation", "CISA KEV priority", "Known-exploited CVEs include KEV urgency, action, due date when available, and scope caveats.", "critical"),
    ("remediation.mitre_mapping", "Remediation", "MITRE mapping", "ATT&CK mappings include mitigation guidance and avoid actor attribution.", "high"),
    ("remediation.no_fake_attribution", "Remediation", "no fake attribution", "Recommendations do not invent CVEs, malware families, threat actors, zero-days, or endorsement claims.", "blocker"),
    ("remediation.false_positive_review", "Remediation", "false-positive review", "Every finding has a false-positive checklist and suppression remains explicit/reversible.", "critical"),
    ("apple_diagnostics.export_menu", "Apple Diagnostics", "export menu", "Reports menu and finding actions expose Apple Diagnostics Evidence Export.", "high"),
    ("apple_diagnostics.package_generation", "Apple Diagnostics", "package generation", "Apple evidence export writes a local package with manifest, hashes, and chain-of-custody metadata.", "critical"),
    ("apple_diagnostics.privacy_redaction", "Apple Diagnostics", "privacy redaction", "Apple evidence export supports redaction and requires privacy review before sharing.", "blocker"),
    ("reports.recommended_fixes", "Reports", "recommended fixes in reports", "HTML, JSON, Word, and Excel exports include recommended fixes and source mappings.", "critical"),
    ("poam.remediation_tracking", "Remediation", "POA&M conversion", "Recommended fixes can be converted into POA&M/remediation tracking rows.", "high"),
    ("integrity.manifest_exists", "Integrity", "manifest exists", "Integrity manifest exists for current mode or reports exact missing-manifest state.", "high"),
    ("integrity.modified_files_classified", "Integrity", "modified files classified", "Every modified file is classified as approved, unapproved, excluded, or stale manifest.", "blocker"),
    ("integrity.approved_change_rebaseline", "Integrity", "approved change rebaseline", "Approved changes can be reviewed and explicitly rebaselined without silent trust.", "blocker"),
    ("integrity.signature_context", "Integrity", "signature context", "Unsigned source mode is contextual while unsigned release artifacts are flagged.", "blocker"),
    ("integrity.no_silent_trust", "Integrity", "no silent trust", "Modified files are never silently trusted without approved review and baseline update.", "blocker"),
    ("integrity.exclusions_valid", "Integrity", "runtime mutable exclusions", "Runtime mutable files are excluded from source integrity manifests.", "high"),
    ("integrity.files_match_manifest", "Integrity", "files match manifest", "Source/package files match signed canonical manifest.", "blocker"),
    ("integrity.canonical_manifest_signature_valid", "Integrity", "canonical manifest signature valid", "Canonical manifest signature verifies for the selected policy.", "blocker"),
    ("integrity.canonical_files_match_manifest", "Integrity", "canonical files match manifest", "Source/package files match signed canonical manifest.", "blocker"),
    ("integrity.release_artifact_signature_valid", "Integrity", "release artifact signature valid", "Dist artifacts are signed when release mode requires them.", "blocker"),
    ("integrity.release_artifacts_match", "Integrity", "release artifacts match", "Dist artifact hashes match signed artifact manifest.", "blocker"),
    ("integrity.unsigned_source_context", "Integrity", "unsigned source context", "Unsigned source checkout is contextual, not a false release failure.", "medium"),
    ("integrity.release_verification_evidence", "Integrity", "release verification evidence", "Release evidence is present when release mode requires it.", "high"),
    ("integrity.policy_resolved", "Integrity", "policy resolved", "Integrity policy resolves through the canonical authority.", "blocker"),
    ("integrity.canonical_manifest_exists", "Integrity", "canonical manifest exists", "Canonical integrity manifest exists for the selected policy.", "blocker"),
    ("integrity.signed_manifest_valid", "Integrity", "signed manifest valid", "Canonical manifest signature validates before trust is established.", "blocker"),
    ("integrity.developer_machine_identity_exists", "Integrity", "developer-machine identity", "Trusted developer-machine registry exists and loads.", "blocker"),
    ("integrity.developer_machine_signature_valid", "Integrity", "developer-machine signature", "Manifest signature verifies against an enrolled developer-machine public key.", "blocker"),
    ("integrity.signing_machine_authorized", "Integrity", "signing machine authorized", "Signing only occurs on an enrolled developer machine.", "blocker"),
    ("integrity.manifest_path_consistency", "Integrity", "manifest path consistency", "All integrity components validate the same canonical manifest.", "blocker"),
    ("integrity.no_unknown_status", "Integrity", "classified status", "Integrity status resolver returns a concrete trust state.", "blocker"),
    ("integrity.no_pass_with_failed_evidence", "Integrity", "no pass with failed evidence", "Integrity checks do not pass while evidence status is failed.", "blocker"),
    ("integrity.generated_artifacts_excluded", "Integrity", "generated artifacts excluded", "Generated audit docs, egg-info, sqlite, temp, and cache files do not cause source mismatch.", "high"),
    ("freshness.timestamps", "Freshness", "data freshness", "Freshness timestamps are timezone-aware or explicitly unavailable.", "critical"),
    ("ui.controls", "Reports/UI", "UI control audit", "Visible controls are enabled/connected or explained.", "blocker"),
    ("ui.buttons.inventory", "Reports/UI", "button inventory", "Visible/source buttons are inventoried for layout review.", "medium"),
    ("ui.buttons.no_overlap", "Reports/UI", "button overlap", "Visible buttons do not overlap sibling controls.", "blocker"),
    ("ui.buttons.no_cropping", "Reports/UI", "button cropping", "Button text is not clipped by its geometry.", "blocker"),
    ("ui.buttons.size_policy", "Reports/UI", "button size policy", "Buttons avoid unsafe fixed sizes and oversized heights.", "high"),
    ("ui.buttons.tooltip_accessibility", "Reports/UI", "button tooltip/accessibility", "Long and icon-only buttons provide tooltip/accessibility fallback.", "high"),
    ("ui.buttons.navigation_proportional", "Reports/UI", "navigation button proportions", "Navigation buttons share compact, proportional dimensions.", "medium"),
    ("ui.buttons.action_rows_responsive", "Reports/UI", "responsive action rows", "Crowded action rows wrap or stack instead of overflowing.", "high"),
    ("ui.buttons.visible_connected", "Reports/UI", "visible button callbacks", "Visible buttons have callbacks or disabled-state explanations.", "blocker"),
    ("ui.buttons.functional_actions", "Reports/UI", "functional UI actions", "Critical protection buttons call real backends, record results, and refresh status.", "blocker"),
    ("ui.antiransomware_panel_instantiates", "Reports/UI", "Anti-Ransomware panel callback contract", "Panel construction has every required public callback.", "blocker"),
    ("ui.antiransomware_install_button_connected", "Reports/UI", "Anti-Ransomware install action", "Install button resolves to the canonical panel method.", "blocker"),
    ("ui.active_protection_install_button_connected", "Reports/UI", "Active Protection install action", "Dashboard and health install actions are connected.", "blocker"),
    ("ui.active_protection_repair_button_connected", "Reports/UI", "Active Protection repair action", "Dashboard and health repair actions are connected.", "blocker"),
    ("ui.no_missing_button_callbacks", "Reports/UI", "no missing callbacks", "Registered production callbacks all exist.", "blocker"),
    ("ui.help_menu_button_proportional", "Reports/UI", "Help Menu button proportional", "Global Help Menu button is compact, unique, accessible, and does not crop or dominate sidebar navigation.", "high"),
    ("ui.help_menu_bottom_left", "Reports/UI", "Help Menu bottom-left", "Global Help Menu button is unique, compact, connected, and pinned to the sidebar utility footer instead of primary navigation.", "high"),
    ("ui.dashboard_severity_navigation", "Reports/UI", "dashboard severity navigation", "Dashboard severity cards are actionable and route to filtered Findings view.", "blocker"),
    ("family_safety.wizard_questions", "Family Safety", "wizard questions", "Family Safety wizard questionnaire loads with help text and options.", "blocker"),
    ("family_safety.recommendation_engine", "Family Safety", "recommendation engine", "Family Safety recommendation engine returns explainable profiles and proposed changes.", "blocker"),
    ("family_safety.preview_required", "Family Safety", "preview required", "Wizard requires review before apply and exposes every proposed change.", "blocker"),
    ("family_safety.apply_transaction", "Family Safety", "apply transaction", "Wizard apply flow snapshots settings, applies selected changes only, bumps version, and verifies sync.", "blocker"),
    ("family_safety.revert_snapshot", "Family Safety", "revert snapshot", "Wizard restore flow previews and restores only wizard-changed MSAA setting paths.", "high"),
    ("family_safety.report_export", "Family Safety", "configuration report export", "Wizard exports recommendation/apply reports with manual review and standards alignment.", "high"),
    ("family_safety.no_silent_changes", "Family Safety", "no silent changes", "Wizard never applies settings without explicit confirmation.", "blocker"),
    ("family_safety.settings_sync_after_apply", "Family Safety", "settings sync after apply", "Settings reconciliation remains aligned after wizard apply.", "blocker"),
]


def build_registry() -> list[FunctionalCheck]:
    checks: list[FunctionalCheck] = []
    for check_id, area, name, description, severity in FEATURES:
        test_type = check_id.split(".", 1)[0]
        if test_type == "scan":
            test_type = "smoke"
        checks.append(
            FunctionalCheck(
                check_id=check_id,
                feature_area=area,
                name=name,
                description=description,
                severity_if_failed=severity,
                test_type=test_type,
                expected_result="Behavior verified by automated pre-UAT audit.",
            )
        )
    return checks
