import SwiftUI
import MSAAAssuranceCore

@main struct MSAAAssuranceApplication: App { var body: some Scene { WindowGroup { AssuranceRootView() }.windowStyle(.titleBar) } }

private enum Page:String,CaseIterable,Identifiable { case dashboard="Assurance Dashboard",controls="Controls",collectors="Collector Health",validation="Validation",export="Evidence Export",about="About & Limitations";var id:String{rawValue} }
struct AssuranceRootView:View {
    @State private var page:Page? = .dashboard
    var body:some View { NavigationSplitView { List(Page.allCases,selection:$page){Text($0.rawValue).tag($0)}.navigationTitle("MSAA") } detail: { Group { switch page ?? .dashboard { case .dashboard:DashboardView();case .controls:ControlsView();case .collectors:CollectorsView();case .validation:ValidationView();case .export:ExportView();case .about:LimitationsView() } }.padding().frame(minWidth:700,minHeight:500) } }
}
struct DashboardView:View { var body:some View { VStack(alignment:.leading,spacing:16){Text("Assurance Dashboard").font(.largeTitle);Text("Silence is not proof of safety.").font(.headline);Grid(alignment:.leading){GridRow{StatusTile("Passing",0,.green);StatusTile("Failed",0,.red);StatusTile("Degraded",0,.orange)};GridRow{StatusTile("Stale",0,.yellow);StatusTile("Unknown",6,.gray);StatusTile("Excepted",0,.blue)}};Divider();Label("Evidence chain: never assessed",systemImage:"link.badge.plus");Label("Policy: no verified profile loaded",systemImage:"doc.badge.ellipsis");Text("Controls remain unknown until fresh evidence and healthy collector heartbeats satisfy every required dimension.").foregroundStyle(.secondary)}.accessibilityElement(children:.contain) } }
struct StatusTile:View {let title:String;let count:Int;let color:Color;init(_ t:String,_ c:Int,_ color:Color){title=t;count=c;self.color=color};var body:some View{VStack(alignment:.leading){Text(title);Text("\(count)").font(.title.bold())}.padding().frame(maxWidth:.infinity,alignment:.leading).background(color.opacity(0.14),in:RoundedRectangle(cornerRadius:10)).accessibilityLabel("\(title) controls: \(count)")}}
struct ControlsView:View {var body:some View{ContentUnavailableView("No policy loaded",systemImage:"checklist",description:Text("Import a verified production profile or explicitly enable an unverified development profile."))}}
struct CollectorsView:View {var body:some View{VStack(alignment:.leading){Text("Collector Health").font(.largeTitle);Text("No collector heartbeat has been recorded. Dependent controls cannot pass.");Spacer()}}}
struct ValidationView:View {@State var confirm=false;var body:some View{VStack(alignment:.leading,spacing:12){Text("Safe Validation").font(.largeTitle);Text("Built-in tests operate only in an MSAA-owned directory. Synthetic results are never production evidence.");Button("Run synthetic liveness validation"){confirm=true}.confirmationDialog("Run bounded synthetic validation?",isPresented:$confirm){Button("Run Test"){};Button("Cancel",role:.cancel){}}.keyboardShortcut(.defaultAction);Spacer()}}}
struct ExportView:View {var body:some View{VStack(alignment:.leading,spacing:12){Text("Evidence Export").font(.largeTitle);Text("Export requires an explicit destination. The signed manifest, chain, expiration, simulation status, and policy status are independently verifiable.");Button("Select Export Location…"){}.disabled(true).help("Enabled after evidence is available");Spacer()}}}
struct LimitationsView:View {var body:some View{ScrollView{VStack(alignment:.leading,spacing:12){Text("About & Limitations").font(.largeTitle);Text("MSAA measures whether defined controls are configured, operating, observable, tested, and recoverable using fresh evidence.");Group{Text("MSAA cannot guarantee that a device is uncompromised.");Text("A passing control does not prove the absence of all attacks.");Text("Simulated evidence is not production evidence.");Text("Standards mappings do not constitute certification.");Text("Local software cannot establish absolute trust when the underlying platform is fully compromised.");Text("Recovery of an MSAA fixture does not prove full-system recoverability.");Text("Endpoint Security observation requires supported APIs and Apple-granted entitlements.")}.foregroundStyle(.secondary)}}}}
