import CryptoKit
import Foundation
@testable import MSAAAssuranceCore

private enum SelfTestFailure:Error { case failed(String) }
private func expect(_ condition:@autoclosure () throws -> Bool,_ message:String="expectation failed")throws { if try !condition(){throw SelfTestFailure.failed(message)} }
private func expectThrows(_ operation:() throws -> Any)throws { do {_ = try operation();throw SelfTestFailure.failed("expected an error")}catch is SelfTestFailure{throw SelfTestFailure.failed("expected an error")}catch{} }

@main struct AssuranceTests {
    let now=Date(timeIntervalSince1970:1_700_000_000)
    func draft(_ sequence:UInt64,_ previous:String=Canonical.zeroDigest,_ state:DimensionState = .pass,_ simulation:SimulationStatus = .production,_ expires:Date?=nil)->EvidenceObservation { .init(evidenceID:"e-\(sequence)",sequenceNumber:sequence,controlID:"C-1",dimension:.configuration,evidenceType:"status",sourceCollectorID:"collector",sourceCollectorVersion:"1",observedAt:now,recordedAt:now,expiresAt:expires ?? now.addingTimeInterval(300),result:state,reasonCode:state == .pass ? .requirementSatisfied:.requirementNotSatisfied,humanReadableSummary:"Allowlisted status metadata.",rawEvidenceDigest:String(repeating:"a",count:64),previousRecordDigest:previous,policyVersion:"1",applicationVersion:"1",hostIdentifier:"pseudonym",simulationStatus:simulation,privacyClassification:"system-metadata") }
    func canonicalDeterminismAndDigest()throws{try expect(try Canonical.data(draft(1)) == Canonical.data(draft(1)));try expect(try Canonical.recordDigest(draft(1)).count == 64)}
    func validModifiedDeletedReorderedAndDuplicateChains()throws {let a=try EvidenceChain.append(draft(1),to:[]);let b=try EvidenceChain.append(draft(2,a.recordDigest),to:[a]);try expect(EvidenceChain.verify([a,b],now:now).valid);try expect(!EvidenceChain.verify([b,a],now:now).valid);try expect(!EvidenceChain.verify([b],now:now).valid);try expect(!EvidenceChain.verify([a,a],now:now).valid);try expect(!EvidenceChain.verify([a,b.withDigest("bad")],now:now).valid)}
    func expirationAndSimulationAreReported()throws{let a=try EvidenceChain.append(draft(1,.init(repeating:"0",count:64),.pass,.simulated,now.addingTimeInterval(-1)),to:[]);let r=EvidenceChain.verify([a],now:now);try expect(r.expiredEvidence == 1);try expect(r.simulatedEvidence == 1)}
    func checkpointSignatureAndWrongKey()throws{let signer=try InMemoryTestSigner();let data=Data("checkpoint".utf8);let sig=try signer.sign(data);try expect(SignatureVerifier.verify(data,metadata:sig));try expect(!SignatureVerifier.verify(Data("altered".utf8),metadata:sig))}
    func exceptionValidation()throws{try expectThrows {try ControlException(exceptionID:"x",controlID:"c",rationale:"",approvingAuthority:"test-role",createdAt:now,effectiveAt:now,expiresAt:now.addingTimeInterval(1),compensatingControlDescription:"fixture",ticketReference:"TEST-1",status:"active",evidenceReferences:[])}}
    func safePath() throws{try expect(SafePath.normalizedExport(URL(string:"https://example.invalid")!) == nil);try expect(SafePath.normalizedExport(URL(fileURLWithPath:"/tmp/msaa-test")) != nil)}
    func redactionIsBounded() throws{let output=FixedStatusCollector.redact(Data((String(repeating:"x",count:1000)+"\u{1b}[31m").utf8));try expect(output.utf8.count <= 512);try expect(!output.contains("\u{1b}"))}
    func sixInitialControlsAndUnknownWithoutEvidence() throws{let controls=InitialProfile.controls(now:now);try expect(controls.count == 6);for c in controls{let r=Evaluator.evaluate(c,evidence:[],collectors:[],now:now);try expect(r.overallState != .pass)}}
    func passRequiresAllFreshProductionDimensionsAndHealthyCollector()throws {let c=InitialProfile.controls(now:now)[0];let health=CollectorHealth(collectorID:c.requiredCollectorIDs[0],version:"1",capabilities:[],lastStartedAt:now,lastSuccessfulObservationAt:now,lastHeartbeatAt:now,currentState:.healthy,errorReasonCode:nil,droppedEventCount:0,sequenceGapCount:0,permissionState:"notRequired",simulationStatus:.production);var records:[EvidenceObservation]=[];for (i,d) in Dimension.allCases.enumerated(){var value=draft(UInt64(i+1),records.last?.recordDigest ?? Canonical.zeroDigest);value = EvidenceObservation(evidenceID:value.evidenceID,sequenceNumber:value.sequenceNumber,controlID:c.controlID,dimension:d,evidenceType:value.evidenceType,sourceCollectorID:health.collectorID,sourceCollectorVersion:"1",observedAt:now,recordedAt:now,expiresAt:now.addingTimeInterval(300),result:.pass,reasonCode:.requirementSatisfied,humanReadableSummary:"fresh",rawEvidenceDigest:value.rawEvidenceDigest,previousRecordDigest:value.previousRecordDigest,policyVersion:"1",applicationVersion:"1",hostIdentifier:"p",simulationStatus:.production,privacyClassification:"system-metadata");records.append(try EvidenceChain.append(value,to:records))};try expect(Evaluator.evaluate(c,evidence:records,collectors:[health],now:now).overallState == .pass);let expired=CollectorHealth(collectorID:health.collectorID,version:"1",capabilities:[],lastStartedAt:now,lastSuccessfulObservationAt:now,lastHeartbeatAt:now.addingTimeInterval(-7200),currentState:.healthy,errorReasonCode:nil,droppedEventCount:0,sequenceGapCount:0,permissionState:"notRequired",simulationStatus:.production);try expect(Evaluator.evaluate(c,evidence:records,collectors:[expired],now:now).overallState == .degraded)}
    func recoveryFixture()throws{let root=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString);defer{try? FileManager.default.removeItem(at:root)};try expect(try ValidationHarness.recoveryFixture(in:root).result == .pass)}
    func policyRejectsUnsupportedUnknownAndUnsignedProduction()throws{let c=InitialProfile.controls(now:now);let profile=PolicyProfile(schemaVersion:"1.0",profileID:"dev",profileVersion:"1",controls:c,signature:nil);let data=try Canonical.data(profile);_ = try PolicyImporter.load(data,developmentMode:true);try expectThrows {try PolicyImporter.load(data,developmentMode:false)};let unknown=try JSONSerialization.data(withJSONObject:["schemaVersion":"1.0","profileID":"x","profileVersion":"1","controls":[],"unexpected":true]);try expectThrows {try PolicyImporter.load(unknown,developmentMode:true)};let unsupported=try JSONSerialization.data(withJSONObject:["schemaVersion":"2.0","profileID":"x","profileVersion":"1","controls":[]]);try expectThrows {try PolicyImporter.load(unsupported,developmentMode:true)}}
    func exportVerificationAndAlteration()throws{let root=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString);defer{try? FileManager.default.removeItem(at:root)};let record=try EvidenceChain.append(draft(1),to:[]);let input=BundleInputs(controls:InitialProfile.controls(now:now),evaluations:[],evidence:[record],collectors:[],validations:[],exceptions:[],policyID:"dev",policyVersion:"1",policySignatureStatus:"unverified",hostIdentifier:"pseudonym");try EvidenceBundle.export(input,to:root,signer:try InMemoryTestSigner(),now:now);try expect(try EvidenceBundle.verify(root,now:now).valid);let events=root.appendingPathComponent("evidence-events.jsonl");var changed=try Data(contentsOf:events);changed.append(0x20);try changed.write(to:events);try expectThrows {try EvidenceBundle.verify(root,now:now)}}
    static func main() throws {
        let tests=AssuranceTests()
        try tests.canonicalDeterminismAndDigest();try tests.validModifiedDeletedReorderedAndDuplicateChains()
        try tests.expirationAndSimulationAreReported();try tests.checkpointSignatureAndWrongKey()
        try tests.exceptionValidation();try tests.safePath();try tests.redactionIsBounded()
        try tests.sixInitialControlsAndUnknownWithoutEvidence();try tests.passRequiresAllFreshProductionDimensionsAndHealthyCollector()
        try tests.recoveryFixture();try tests.policyRejectsUnsupportedUnknownAndUnsignedProduction();try tests.exportVerificationAndAlteration()
        print("PASS: 12 native assurance self-tests")
    }
}
