import Foundation

public struct ValidationResult:Codable,Sendable { public let testID,testVersion,executionID:String;public let startedAt,completedAt:Date;public let expectedObservations,actualObservations:[String];public let result:DimensionState;public let failureReason:String?;public let collectorHealthAtExecution:[CollectorHealth];public let simulationStatus:SimulationStatus;public let evidenceReferences:[String] }
public enum ValidationHarness {
    public static func syntheticLiveness(collector:SyntheticEventCollector=SyntheticEventCollector()) async -> ValidationResult { let start=Date(),execution=UUID().uuidString;let(output,health)=await collector.collect();return .init(testID:"synthetic-liveness",testVersion:"1.0",executionID:execution,startedAt:start,completedAt:Date(),expectedObservations:["correlated benign event"],actualObservations:[output.summary],result:output.result,failureReason:nil,collectorHealthAtExecution:[health],simulationStatus:.simulated,evidenceReferences:[]) }
    public static func recoveryFixture(in ownedDirectory:URL) throws -> ValidationResult {
        let start=Date(),execution=UUID().uuidString;try FileManager.default.createDirectory(at:ownedDirectory,withIntermediateDirectories:true,attributes:[.posixPermissions:0o700]);let original=Data("MSAA benign recovery fixture v1".utf8),backup=ownedDirectory.appendingPathComponent("fixture.backup"),working=ownedDirectory.appendingPathComponent("fixture.test");try original.write(to:backup,options:.atomic);try original.write(to:working,options:.atomic);try Data("modified fixture".utf8).write(to:working,options:.atomic);try FileManager.default.removeItem(at:working);try FileManager.default.copyItem(at:backup,to:working);let passed=Canonical.sha256(try Data(contentsOf:working))==Canonical.sha256(original);return .init(testID:"fixture-recovery",testVersion:"1.0",executionID:execution,startedAt:start,completedAt:Date(),expectedObservations:["restored digest equals original fixture digest"],actualObservations:[passed ? "digest restored":"digest mismatch"],result:passed ? .pass:.fail,failureReason:passed ? nil:"recovery digest mismatch",collectorHealthAtExecution:[],simulationStatus:.development,evidenceReferences:[])
    }
}
