from __future__ import annotations

from fnmatch import fnmatch
from pathlib import Path
from typing import Iterable, TypedDict


class ExclusionEntry(TypedDict):
    pattern: str
    reason: str
    category: str
    allowed_in_release_manifest: bool
    applies_to_policy: list[str]


EXCLUSION_ENTRIES: list[ExclusionEntry] = [
    {"pattern": "__pycache__/", "reason": "Python bytecode cache", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": "*.pyc", "reason": "Python bytecode cache", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": ".pytest_cache/", "reason": "pytest runtime cache", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": ".ruff_cache/", "reason": "ruff runtime cache", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": ".mypy_cache/", "reason": "mypy runtime cache", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": "build/", "reason": "local build output", "category": "build_artifact", "allowed_in_release_manifest": False},
    {"pattern": ".build/", "reason": "local native build output", "category": "build_artifact", "allowed_in_release_manifest": False},
    {"pattern": "dist/", "reason": "local distribution output", "category": "build_artifact", "allowed_in_release_manifest": False},
    {"pattern": "*.egg-info/", "reason": "packaging metadata generated by build tools", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "**/*.egg-info/", "reason": "packaging metadata generated by build tools", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "macos_security_audit_agent.egg-info/", "reason": "packaging metadata generated by build tools", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": ".git/", "reason": "source control metadata", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": "venv/", "reason": "local virtual environment", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": ".venv/", "reason": "local virtual environment", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": "logs/", "reason": "runtime logs", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "reports/", "reason": "generated report output", "category": "report_output", "allowed_in_release_manifest": False},
    {"pattern": "reports/pre_uat/", "reason": "generated Pre-UAT output", "category": "report_output", "allowed_in_release_manifest": False},
    {"pattern": "docs/PRE_UAT_*_AUDIT.md", "reason": "generated Pre-UAT audit document", "category": "report_output", "allowed_in_release_manifest": False},
    {"pattern": "docs/*_AUDIT.md", "reason": "MSAA generated audit document", "category": "report_output", "allowed_in_release_manifest": False},
    {"pattern": ".tmp_pre_uat/", "reason": "temporary Pre-UAT working directory", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": ".tmp_pre_uat/**", "reason": "temporary Pre-UAT working directory", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "release_evidence/", "reason": "release evidence output", "category": "report_output", "allowed_in_release_manifest": False},
    {"pattern": "diagnostics/", "reason": "generated diagnostics", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "snapshots/", "reason": "generated snapshots", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "evidence/", "reason": "generated evidence output", "category": "report_output", "allowed_in_release_manifest": False},
    {"pattern": "clean_install_evidence/", "reason": "generated clean install evidence", "category": "report_output", "allowed_in_release_manifest": False},
    {"pattern": "Application Support/", "reason": "runtime application support data", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.sqlite", "reason": "runtime sqlite database", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.sqlite3", "reason": "runtime sqlite database", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.sqlite3-wal", "reason": "sqlite write-ahead log", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.sqlite3-shm", "reason": "sqlite shared memory file", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "release_audit.sqlite3", "reason": "release audit runtime database", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.db", "reason": "runtime database", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.db-journal", "reason": "database journal", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.sqlite-journal", "reason": "sqlite journal", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.sqlite3-journal", "reason": "sqlite journal", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.db-wal", "reason": "database write-ahead log", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.sqlite-wal", "reason": "sqlite write-ahead log", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.db-shm", "reason": "database shared memory file", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.sqlite-shm", "reason": "sqlite shared memory file", "category": "runtime_db", "allowed_in_release_manifest": False},
    {"pattern": "*.log", "reason": "runtime log", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "*.tmp", "reason": "temporary file", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "*.temp", "reason": "temporary file", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": ".DS_Store", "reason": "macOS Finder metadata", "category": "cache", "allowed_in_release_manifest": False},
    {"pattern": "msaa_integrity_manifest.json", "reason": "legacy integrity manifest", "category": "legacy", "allowed_in_release_manifest": False},
    {"pattern": "package_integrity_manifest.json", "reason": "package integrity manifest", "category": "legacy", "allowed_in_release_manifest": False},
    {"pattern": "integrity_manifest.json", "reason": "runtime integrity manifest", "category": "legacy", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/security/integrity_manifest.json", "reason": "legacy source integrity manifest", "category": "legacy", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/security/integrity_manifest.json.sig", "reason": "legacy source integrity signature", "category": "legacy", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/development_manifest.json", "reason": "legacy development integrity manifest", "category": "legacy_ignored", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/development_manifest.sig", "reason": "legacy development integrity signature", "category": "legacy_ignored", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/release_manifest.json", "reason": "legacy release integrity manifest", "category": "legacy_ignored", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/release_manifest.sig", "reason": "legacy release integrity signature", "category": "legacy_ignored", "allowed_in_release_manifest": False},
    {"pattern": "dist/MSAA_RELEASE_ARTIFACTS.json", "reason": "generated artifact manifest", "category": "build_artifact", "allowed_in_release_manifest": False},
    {"pattern": "dist/MSAA_RELEASE_ARTIFACTS.sig", "reason": "generated artifact signature", "category": "build_artifact", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/trust/*private*", "reason": "private signing key material", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/integrity_manifest.signature.json", "reason": "developer-machine integrity signature bundle", "category": "trust_metadata", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/integrity_manifest.signatures.json", "reason": "legacy YubiKey integrity signature bundle", "category": "legacy", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/trusted_developer_machines.json", "reason": "trusted developer-machine public registry", "category": "trust_metadata", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/yubikey_signatures/", "reason": "optional legacy YubiKey signature artifacts", "category": "deprecated_artifact", "allowed_in_release_manifest": False},
    {"pattern": "approved_changes/", "reason": "local approval workflow output", "category": "generated", "allowed_in_release_manifest": False},
    {"pattern": "mac_audit_agent/integrity/approved_source_changes.jsonl", "reason": "append-only local source approval ledger", "category": "trust_metadata", "allowed_in_release_manifest": False},
    {"pattern": ".msaa/", "reason": "local MSAA state", "category": "generated", "allowed_in_release_manifest": False},
]

RUNTIME_MUTABLE_EXCLUSION_PATTERNS = [entry["pattern"] for entry in EXCLUSION_ENTRIES]
for _entry in EXCLUSION_ENTRIES:
    _entry.setdefault("applies_to_policy", ["dev", "pre_release", "public_release", "runtime"])  # type: ignore[typeddict-item]


IMMUTABLE_SOURCE_HINTS = [
    "mac_audit_agent/",
    "docs/",
    "scripts/",
    "tests/",
    "pyproject.toml",
    "requirements.txt",
    "MANIFEST.in",
]


def default_excluded_patterns() -> list[str]:
    return list(RUNTIME_MUTABLE_EXCLUSION_PATTERNS)


def default_exclusion_entries() -> list[ExclusionEntry]:
    return [dict(entry) for entry in EXCLUSION_ENTRIES]


def is_runtime_mutable_path(relative_path: str, patterns: Iterable[str] | None = None) -> bool:
    normalized = str(relative_path).replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    parts = normalized.split("/")
    for pattern in patterns or RUNTIME_MUTABLE_EXCLUSION_PATTERNS:
        clean = pattern.strip()
        if not clean:
            continue
        directory = clean.endswith("/")
        compact = clean.rstrip("/")
        if directory and compact and normalized.startswith(f"{compact}/"):
            return True
        if directory and compact in parts:
            return True
        if fnmatch(normalized, clean) or fnmatch(Path(normalized).name, clean):
            return True
        if compact and compact in parts and "/" not in compact and "*" not in compact:
            return True
    return False


def classify_path_category(relative_path: str) -> str:
    path = str(relative_path).replace("\\", "/")
    suffix = Path(path).suffix.lower()
    parts = set(Path(path).parts)
    if path.startswith("mac_audit_agent/ui/"):
        return "ui"
    if path.startswith("mac_audit_agent/frameworks") or "frameworks" in parts:
        return "framework_mapping"
    if path.startswith("mac_audit_agent/tests/") or "/tests/" in path:
        return "test"
    if suffix in {".html", ".md", ".docx", ".xlsx"} and ("report" in path or "template" in path):
        return "report_template"
    if suffix in {".png", ".jpg", ".jpeg", ".icns", ".ico", ".qss", ".css"} or "assets" in parts:
        return "asset"
    if Path(path).name in {"pyproject.toml", "MANIFEST.in", "requirements.txt"} or "Mac Audit Agent.spec" in path:
        return "packaging"
    if suffix in {".json", ".toml", ".yaml", ".yml", ".plist", ".txt", ".md"}:
        return "config_template"
    return "source"


__all__ = [
    "RUNTIME_MUTABLE_EXCLUSION_PATTERNS",
    "EXCLUSION_ENTRIES",
    "IMMUTABLE_SOURCE_HINTS",
    "default_exclusion_entries",
    "default_excluded_patterns",
    "is_runtime_mutable_path",
    "classify_path_category",
]
